package co.com.bancolombia.security.dinamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "aut-bancolombiapay-ambiente-qa-tokenizacion")
public class TokenEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "relation_id")
    private String relationalId;
    @DynamoDBAttribute(attributeName = "third_app")
    private String thirdApp;
    @DynamoDBAttribute(attributeName = "product")
    private String product;
    @DynamoDBAttribute(attributeName = "cid")
    private String cid;
    @DynamoDBAttribute(attributeName = "status")
    private String status;
    @DynamoDBAttribute(attributeName = "product_type")
    private String productType;
    @DynamoDBAttribute(attributeName = "creation_date")
    private String creationDate;
    @DynamoDBAttribute(attributeName = "update_date")
    private String updateDate;
}
